[package]
name = "coalescence"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "~0.4" }

[[example]]
name = "main"

[dev-dependencies]
rprompt = { version = "~1.0" }
env_logger = { version = "~0.9" }
pretty_assertions = { version = "~1.0" }
